import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

export async function docsCommand(): Promise<void> {
  console.log('📖 FORGE Documentation Generator\n');

  try {
    if (!existsSync('Anchor.toml')) {
      console.error('❌ Not in an Anchor project directory');
      process.exit(1);
    }

    const idlPath = join('target', 'idl', `${getProgramName()}.json`);
    if (!existsSync(idlPath)) {
      console.error('❌ IDL not found. Run "anchor build" first.');
      process.exit(1);
    }

    const idl = JSON.parse(readFileSync(idlPath, 'utf8'));
    const docsDir = join('docs');
    mkdirSync(docsDir, { recursive: true });

    let docs = `# ${idl.name} - API Documentation\n\n`;
    docs += `Generated by FORGE\n\n`;
    docs += `## Program ID\n\`\`\`\n${getProgramId()}\n\`\`\`\n\n`;

    if (idl.instructions) {
      docs += `## Instructions\n\n`;
      for (const instruction of idl.instructions) {
        docs += `### ${instruction.name}\n\n`;
        if (instruction.accounts) {
          docs += `**Accounts:**\n\n`;
          for (const account of instruction.accounts) {
            docs += `- \`${account.name}\`: ${account.isMut ? 'Mutable' : 'Read-only'} ${account.isSigner ? 'Signer' : ''}\n`;
          }
          docs += '\n';
        }
        if (instruction.args) {
          docs += `**Arguments:**\n\n`;
          for (const arg of instruction.args) {
            docs += `- \`${arg.name}\`: ${arg.type}\n`;
          }
          docs += '\n';
        }
      }
    }

    if (idl.accounts) {
      docs += `## Accounts\n\n`;
      for (const account of idl.accounts) {
        docs += `### ${account.name}\n\n`;
        if (account.type?.fields) {
          for (const field of account.type.fields) {
            docs += `- \`${field.name}\`: ${field.type}\n`;
          }
        }
        docs += '\n';
      }
    }

    writeFileSync(join(docsDir, 'API.md'), docs);
    console.log('✅ Documentation generated: docs/API.md');

  } catch (error: any) {
    console.error('❌ Documentation generation failed');
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
}

function getProgramName(): string {
  try {
    const anchorToml = readFileSync('Anchor.toml', 'utf8');
    const match = anchorToml.match(/\[programs\.localnet\]\s*([^=]+)\s*=\s*"([^"]+)"/);
    return match ? match[1] : 'my-program';
  } catch {
    return 'my-program';
  }
}

function getProgramId(): string {
  try {
    const anchorToml = readFileSync('Anchor.toml', 'utf8');
    const match = anchorToml.match(/\[programs\.localnet\]\s*([^=]+)\s*=\s*"([^"]+)"/);
    return match ? match[2] : 'Unknown';
  } catch {
    return 'Unknown';
  }
}
